### PR TITLE
Parquet library

### PR DESCRIPTION
**Pull request by michoecho**
Continuation of #93 and #92, cleaned up.

### CODE REVIEW

**Comment by michoecho** [comment]
I have done a whole lot of shuffling the code around, moving it between files, moving it between commits, renaming, etc. Besides being moved, the reader parts haven't changed much in the process though, so if you read #92 before, you can just skip them. Please take a look at the general code layout though.

The new (writer) parts are in commits `parquet: Add plain and dictionary encoders` and later, and also the writer halves of `compression.cc` and `logical_type.cc`.

**Comment by michoecho** [comment]
Note: non-essential data encodings (that is, ones not used in Apache Arrow) remain unimplemented (even though they seem useful and deserve to be added). Adding them should be very easy (I think I could do them all in a day or two, because encoding code is self-contained and can be copied from elsewhere), but I haven't done that yet, because the more of them, the more work potential refactorings take. (For example, this week I have changed the decoder interface from std::variant-based one to an usual abstract class, and changed the template parameter from the output type to the parquet enum. Stuff like that). When the gains some approval, I will plug other encodings in. I hope that's alright?
Same for compressions other that gzip and snappy.

**Comment by psarna** [comment]
The code generally looks good for pushing, but commit messages need to be updated - each one needs to have at least a couple of sentences explaining what happens in the commit, assuming that the reviewer will not be familiar with the project in general (which will be the case when we push this to scylla). I added short helper questions to each commit message that must be amended:

```
commit 33d29d295f374caf46ca2f692af4c7c52b06ed5d
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Tue Mar 24 21:21:39 2020 +0100

    parquet: Add file_reader
    
    --- What's file_reader? What are its capabilities?

commit f61a2fbcadd80aaa27a2bbd43e155ea858ced946
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Thu Apr 23 02:52:17 2020 +0200

    parquet: Add reader_schema
    
    --- What's reader_schema? Why do we need this?

commit 185d39cedbf703c26096677cd8201a42fe8d0066
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Thu Apr 23 02:51:57 2020 +0200

    parquet: Add logical_type
    
    --- What's a logical_type? Where is it useful?

commit cc67dc80e2a83f5fac28413afafb98bd28bbaf22
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Wed Apr 22 21:15:51 2020 +0200

    parquet: Add column_chunk_reader
    
    --- What does column_chunk_reader do exactly, i.e. what does "chunk" mean in Parquet nomenclature?

commit f2cd53dc28a10acb24653605df24e2821636b689
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Thu Apr 23 03:37:35 2020 +0200

    parquet: Add plain, dictionary and RLE decoders
    
    --- What are these decoders used for? What does RLE stand for?

commit 3812a0f097ba16d58bb66950bc571d781b0938b1
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Wed Apr 22 21:14:21 2020 +0200

    parquet: Add thrift serdes routines
    
    --- let's not save up on commit message characters and expand serdes to serialization/deserialization

commit cf639461b753fb03d6dd072c3ce3aeff5b277456
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Wed Apr 22 00:23:28 2020 +0200

    parquet: Add compression
    
    --- which algorithms? What does it compress?

commit ce2487fdc96ff818457728ff6b9aed3441d6d887
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Wed Apr 22 21:56:37 2020 +0200

    parquet: Add exception.hh
    
    --- What kinds of expections are added? What do they mean?

commit 5f48bab323da5ab677707f060ab6ab2b38832a32
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Wed Apr 22 21:55:21 2020 +0200

    parquet: Add overloaded.hh
    
    --- Most C++ people will know what it means, but we need a short explanation anyway.

commit 39c0639260ecc56da6bb1838cc44b5b7afd7a527
Author: Michał Chojnowski <mc394134@students.mimuw.edu.pl>
Date:   Tue Apr 21 19:36:55 2020 +0200

    parquet: Add bytes.hh
    
    --- What's "bytes"? Why do we need the header?
``

**Comment by psarna** [comment]
Also, we still have a choice - migrate to Scylla or migrate to a separate project, integrated with CMake and able to accept a Seastar path via cmake config. Depending on the decision, this pull request should either be redirected to the scylla repo, or a separate repo should be instantiated.
Preferences? @michoecho @prawilny?

**Comment by michoecho** [comment]
> Also, we still have a choice - migrate to Scylla or migrate to a separate project, integrated with CMake and able to accept a Seastar path via cmake config. Depending on the decision, this pull request should either be redirected to the scylla repo, or a separate repo should be instantiated.
> Preferences? @michoecho @prawilny?

This library is an independent entity and I see no reasons to make it a part of Scylla. If you are allowing us to make a separate repository after all, then I am going to do just that.

I will try to migrate the library to a new repository today, and plug it into Scylla (together with Samvel's changes rewritten to use it instead of Arrow) tomorrow.

**Comment by prawilny** [comment]
As Michał is the code's author, I consider his opinion to be binding.

**Comment by michoecho** [comment]
> I will try to migrate the library to a new repository today, and plug it into Scylla (together with Samvel's changes rewritten to use it instead of Arrow) tomorrow.

Update: I haven't managed to finalize the migration today. I still hope to both of the above tomorrow (on Monday, that is).

**Comment by psarna** [comment]
Ok, good. After the migration is done, we'll present the new repo on Scylla and Seastar mailing lists with an introductory e-mail. The repository should be kept on your github account as you're the author, and Scylla will simply make an official fork of it later when it's useful.

**Comment by michoecho** [comment]
Moving to https://github.com/michoecho/parquet4seastar/pull/1

**Comment by michoecho** [comment]
The migration is done, but took more work than expected. I haven't got around to moving Samvel's code from Arrow to my library yet. I will try to do it tomorrow, I guess.

**Pull request closed without merging**
